Fix `cudf_test/iterator_utilities.hpp` (#8126)
Summary:
* Replace `static` by `inline` qualifier for the functions to fix compilation error `error: ‘auto cudf::test::XXX(...)’ defined but not used`.
* Add `iterator_all_nulls` function that returns an iterator which always yields `false`.
* Add `iterator_no_null` function that returns an iterator which always yields `true`.

The two new functions are required in some PRs for testing.

Authors:
  - Nghia Truong (https://github.com/ttnghia)

Approvers:
  - Vukasin Milovanovic (https://github.com/vuule)
  - MithunR (https://github.com/mythrocks)

URL: https://github.com/rapidsai/cudf/pull/8126