Fix debug compile error in gather_struct_tests.cpp (#8554)
Building libcudf in debug resulted in a compile error introduced by #8527 

```
../tests/copying/gather_struct_tests.cpp:87:32: error: suggest parentheses around ‘&&’ within ‘||’ [-Werror=parentheses]
   87 |       assert(gather_index >= 0 && gather_index < gather_map.size() ||
      |              ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This error only shows in a debug build. This PR fixes the this code by applying the parentheses as the error suggests.

Authors:
  - David Wendt (https://github.com/davidwendt)

Approvers:
  - Gera Shegalov (https://github.com/gerashegalov)
  - Nghia Truong (https://github.com/ttnghia)
  - MithunR (https://github.com/mythrocks)

URL: https://github.com/rapidsai/cudf/pull/8554